#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 105
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 63
#define ALIAS_COUNT 0
#define TOKEN_COUNT 34
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 10
#define PRODUCTION_ID_COUNT 15

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_BANG = 2,
  anon_sym_DASH = 3,
  anon_sym_PIPE_PIPE = 4,
  anon_sym_AMP_AMP = 5,
  anon_sym_LT = 6,
  anon_sym_LT_EQ = 7,
  anon_sym_EQ_EQ = 8,
  anon_sym_BANG_EQ = 9,
  anon_sym_GT_EQ = 10,
  anon_sym_GT = 11,
  anon_sym_PLUS = 12,
  anon_sym_DOT = 13,
  anon_sym_reply = 14,
  anon_sym_LPAREN = 15,
  anon_sym_RPAREN = 16,
  anon_sym_SEMI = 17,
  anon_sym_EQ = 18,
  anon_sym_if = 19,
  anon_sym_else = 20,
  anon_sym_LBRACE = 21,
  anon_sym_RBRACE = 22,
  anon_sym_illegal = 23,
  anon_sym_defer = 24,
  anon_sym_on = 25,
  anon_sym_COMMA = 26,
  anon_sym_COLON = 27,
  anon_sym_LT_DASH = 28,
  anon_sym_optional = 29,
  anon_sym_inevitable = 30,
  anon_sym_true = 31,
  anon_sym_false = 32,
  sym_number = 33,
  sym_source_file = 34,
  sym_expression = 35,
  sym_reference = 36,
  sym_unary_expression = 37,
  sym_binary_expression = 38,
  sym__statement = 39,
  sym__imperative_statement = 40,
  sym__declarative_statement = 41,
  sym_reply_statement = 42,
  sym_variable_declaration = 43,
  sym_assign_statement = 44,
  sym_if_statement = 45,
  sym_empty_statement = 46,
  sym_block_statement = 47,
  sym_function_call_statement = 48,
  sym_out_event_statement = 49,
  sym_illegal_statement = 50,
  sym_defer_statement = 51,
  sym_on_statement = 52,
  sym__trigger_formal = 53,
  sym_event = 54,
  sym_type_name = 55,
  sym__scoped_identifier = 56,
  sym__global_scoped_identifier = 57,
  sym_global = 58,
  sym_literal = 59,
  aux_sym_source_file_repeat1 = 60,
  aux_sym_on_statement_repeat1 = 61,
  aux_sym__scoped_identifier_repeat1 = 62,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_BANG] = "!",
  [anon_sym_DASH] = "-",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_GT] = ">",
  [anon_sym_PLUS] = "+",
  [anon_sym_DOT] = ".",
  [anon_sym_reply] = "reply",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_SEMI] = ";",
  [anon_sym_EQ] = "=",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_illegal] = "illegal",
  [anon_sym_defer] = "defer",
  [anon_sym_on] = "on",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON] = ":",
  [anon_sym_LT_DASH] = "<-",
  [anon_sym_optional] = "optional",
  [anon_sym_inevitable] = "inevitable",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [sym_expression] = "expression",
  [sym_reference] = "reference",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym__statement] = "_statement",
  [sym__imperative_statement] = "_imperative_statement",
  [sym__declarative_statement] = "_declarative_statement",
  [sym_reply_statement] = "reply_statement",
  [sym_variable_declaration] = "variable_declaration",
  [sym_assign_statement] = "assign_statement",
  [sym_if_statement] = "if_statement",
  [sym_empty_statement] = "empty_statement",
  [sym_block_statement] = "block_statement",
  [sym_function_call_statement] = "function_call_statement",
  [sym_out_event_statement] = "out_event_statement",
  [sym_illegal_statement] = "illegal_statement",
  [sym_defer_statement] = "defer_statement",
  [sym_on_statement] = "on_statement",
  [sym__trigger_formal] = "_trigger_formal",
  [sym_event] = "event",
  [sym_type_name] = "type_name",
  [sym__scoped_identifier] = "_scoped_identifier",
  [sym__global_scoped_identifier] = "_global_scoped_identifier",
  [sym_global] = "global",
  [sym_literal] = "literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_on_statement_repeat1] = "on_statement_repeat1",
  [aux_sym__scoped_identifier_repeat1] = "_scoped_identifier_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_reply] = anon_sym_reply,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_illegal] = anon_sym_illegal,
  [anon_sym_defer] = anon_sym_defer,
  [anon_sym_on] = anon_sym_on,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LT_DASH] = anon_sym_LT_DASH,
  [anon_sym_optional] = anon_sym_optional,
  [anon_sym_inevitable] = anon_sym_inevitable,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [sym_expression] = sym_expression,
  [sym_reference] = sym_reference,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym__statement] = sym__statement,
  [sym__imperative_statement] = sym__imperative_statement,
  [sym__declarative_statement] = sym__declarative_statement,
  [sym_reply_statement] = sym_reply_statement,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_assign_statement] = sym_assign_statement,
  [sym_if_statement] = sym_if_statement,
  [sym_empty_statement] = sym_empty_statement,
  [sym_block_statement] = sym_block_statement,
  [sym_function_call_statement] = sym_function_call_statement,
  [sym_out_event_statement] = sym_out_event_statement,
  [sym_illegal_statement] = sym_illegal_statement,
  [sym_defer_statement] = sym_defer_statement,
  [sym_on_statement] = sym_on_statement,
  [sym__trigger_formal] = sym__trigger_formal,
  [sym_event] = sym_event,
  [sym_type_name] = sym_type_name,
  [sym__scoped_identifier] = sym__scoped_identifier,
  [sym__global_scoped_identifier] = sym__global_scoped_identifier,
  [sym_global] = sym_global,
  [sym_literal] = sym_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_on_statement_repeat1] = aux_sym_on_statement_repeat1,
  [aux_sym__scoped_identifier_repeat1] = aux_sym__scoped_identifier_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_reply] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_illegal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_defer] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_on] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_optional] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_inevitable] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__imperative_statement] = {
    .visible = false,
    .named = true,
  },
  [sym__declarative_statement] = {
    .visible = false,
    .named = true,
  },
  [sym_reply_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_assign_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_empty_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_block_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_out_event_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_illegal_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_defer_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_on_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__trigger_formal] = {
    .visible = false,
    .named = true,
  },
  [sym_event] = {
    .visible = true,
    .named = true,
  },
  [sym_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym__scoped_identifier] = {
    .visible = false,
    .named = true,
  },
  [sym__global_scoped_identifier] = {
    .visible = false,
    .named = true,
  },
  [sym_global] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_on_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__scoped_identifier_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_event = 1,
  field_expression = 2,
  field_false = 3,
  field_function = 4,
  field_port = 5,
  field_ref = 6,
  field_true = 7,
  field_type = 8,
  field_var = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_event] = "event",
  [field_expression] = "expression",
  [field_false] = "false",
  [field_function] = "function",
  [field_port] = "port",
  [field_ref] = "ref",
  [field_true] = "true",
  [field_type] = "type",
  [field_var] = "var",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 1},
  [6] = {.index = 8, .length = 1},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 3},
  [9] = {.index = 14, .length = 2},
  [10] = {.index = 16, .length = 2},
  [11] = {.index = 18, .length = 2},
  [12] = {.index = 20, .length = 4},
  [13] = {.index = 24, .length = 4},
  [14] = {.index = 28, .length = 6},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_type, 0},
    {field_var, 1},
  [2] =
    {field_function, 0},
  [3] =
    {field_expression, 2},
    {field_var, 0},
  [5] =
    {field_expression, 2},
    {field_true, 4},
  [7] =
    {field_var, 0},
  [8] =
    {field_port, 0},
  [9] =
    {field_event, 2},
    {field_port, 0},
  [11] =
    {field_expression, 2},
    {field_false, 6},
    {field_true, 4},
  [14] =
    {field_event, 3},
    {field_port, 1},
  [16] =
    {field_ref, 2},
    {field_var, 0},
  [18] =
    {field_ref, 1, .inherited = true},
    {field_var, 1, .inherited = true},
  [20] =
    {field_ref, 0, .inherited = true},
    {field_ref, 1, .inherited = true},
    {field_var, 0, .inherited = true},
    {field_var, 1, .inherited = true},
  [24] =
    {field_event, 3},
    {field_port, 1},
    {field_ref, 5, .inherited = true},
    {field_var, 5, .inherited = true},
  [28] =
    {field_event, 3},
    {field_port, 1},
    {field_ref, 5, .inherited = true},
    {field_ref, 6, .inherited = true},
    {field_var, 5, .inherited = true},
    {field_var, 6, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 9,
  [11] = 11,
  [12] = 11,
  [13] = 13,
  [14] = 13,
  [15] = 15,
  [16] = 16,
  [17] = 15,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 20,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 22,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 34,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 61,
  [64] = 60,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 99,
  [102] = 102,
  [103] = 103,
  [104] = 104,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '!', 10,
        '&', 3,
        '(', 23,
        ')', 24,
        '+', 21,
        ',', 30,
        '-', 12,
        '.', 22,
        ':', 31,
        ';', 25,
        '<', 15,
        '=', 27,
        '>', 20,
        '{', 28,
        '|', 7,
        '}', 29,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 9,
        '(', 23,
        ')', 24,
        ',', 30,
        '-', 12,
        '.', 22,
        '<', 4,
        '=', 26,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '!', 5,
        '&', 3,
        ')', 24,
        '+', 21,
        '-', 11,
        '.', 22,
        ';', 25,
        '<', 15,
        '=', 6,
        '>', 20,
        '|', 7,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 3:
      if (lookahead == '&') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(32);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(18);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == '|') ADVANCE(13);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(18);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(19);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(17);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LT_DASH);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'd') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (lookahead == 'f') ADVANCE(3);
      if (lookahead == 'i') ADVANCE(4);
      if (lookahead == 'o') ADVANCE(5);
      if (lookahead == 'r') ADVANCE(6);
      if (lookahead == 't') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'f') ADVANCE(11);
      if (lookahead == 'l') ADVANCE(12);
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'n') ADVANCE(14);
      if (lookahead == 'p') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'f') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_on);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 16:
      if (lookahead == 'p') ADVANCE(24);
      END_STATE();
    case 17:
      if (lookahead == 'u') ADVANCE(25);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 20:
      if (lookahead == 's') ADVANCE(28);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 22:
      if (lookahead == 'v') ADVANCE(30);
      END_STATE();
    case 23:
      if (lookahead == 'i') ADVANCE(31);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(34);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 29:
      if (lookahead == 'g') ADVANCE(36);
      END_STATE();
    case 30:
      if (lookahead == 'i') ADVANCE(37);
      END_STATE();
    case 31:
      if (lookahead == 'o') ADVANCE(38);
      END_STATE();
    case 32:
      if (lookahead == 'y') ADVANCE(39);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_defer);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 36:
      if (lookahead == 'a') ADVANCE(40);
      END_STATE();
    case 37:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 38:
      if (lookahead == 'n') ADVANCE(42);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_reply);
      END_STATE();
    case 40:
      if (lookahead == 'l') ADVANCE(43);
      END_STATE();
    case 41:
      if (lookahead == 'a') ADVANCE(44);
      END_STATE();
    case 42:
      if (lookahead == 'a') ADVANCE(45);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_illegal);
      END_STATE();
    case 44:
      if (lookahead == 'b') ADVANCE(46);
      END_STATE();
    case 45:
      if (lookahead == 'l') ADVANCE(47);
      END_STATE();
    case 46:
      if (lookahead == 'l') ADVANCE(48);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_optional);
      END_STATE();
    case 48:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_inevitable);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_reply] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_illegal] = ACTIONS(1),
    [anon_sym_defer] = ACTIONS(1),
    [anon_sym_on] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_optional] = ACTIONS(1),
    [anon_sym_inevitable] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(93),
    [sym__statement] = STATE(4),
    [sym__imperative_statement] = STATE(4),
    [sym__declarative_statement] = STATE(4),
    [sym_reply_statement] = STATE(4),
    [sym_variable_declaration] = STATE(4),
    [sym_assign_statement] = STATE(4),
    [sym_if_statement] = STATE(4),
    [sym_empty_statement] = STATE(4),
    [sym_block_statement] = STATE(4),
    [sym_function_call_statement] = STATE(4),
    [sym_out_event_statement] = STATE(4),
    [sym_illegal_statement] = STATE(4),
    [sym_defer_statement] = STATE(4),
    [sym_on_statement] = STATE(4),
    [sym_type_name] = STATE(88),
    [sym__scoped_identifier] = STATE(80),
    [sym__global_scoped_identifier] = STATE(80),
    [sym_global] = STATE(75),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_DOT] = ACTIONS(7),
    [anon_sym_reply] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_illegal] = ACTIONS(17),
    [anon_sym_defer] = ACTIONS(19),
    [anon_sym_on] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(25), 1,
      sym_identifier,
    ACTIONS(28), 1,
      anon_sym_DOT,
    ACTIONS(31), 1,
      anon_sym_reply,
    ACTIONS(34), 1,
      anon_sym_SEMI,
    ACTIONS(37), 1,
      anon_sym_if,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(43), 1,
      anon_sym_illegal,
    ACTIONS(46), 1,
      anon_sym_defer,
    ACTIONS(49), 1,
      anon_sym_on,
    STATE(75), 1,
      sym_global,
    STATE(88), 1,
      sym_type_name,
    ACTIONS(23), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(80), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(2), 15,
      sym__statement,
      sym__imperative_statement,
      sym__declarative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_block_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
      sym_on_statement,
      aux_sym_source_file_repeat1,
  [59] = 14,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(19), 1,
      anon_sym_defer,
    ACTIONS(21), 1,
      anon_sym_on,
    ACTIONS(52), 1,
      anon_sym_RBRACE,
    STATE(75), 1,
      sym_global,
    STATE(88), 1,
      sym_type_name,
    STATE(80), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(5), 15,
      sym__statement,
      sym__imperative_statement,
      sym__declarative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_block_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
      sym_on_statement,
      aux_sym_source_file_repeat1,
  [117] = 14,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(19), 1,
      anon_sym_defer,
    ACTIONS(21), 1,
      anon_sym_on,
    ACTIONS(54), 1,
      ts_builtin_sym_end,
    STATE(75), 1,
      sym_global,
    STATE(88), 1,
      sym_type_name,
    STATE(80), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(2), 15,
      sym__statement,
      sym__imperative_statement,
      sym__declarative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_block_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
      sym_on_statement,
      aux_sym_source_file_repeat1,
  [175] = 14,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(19), 1,
      anon_sym_defer,
    ACTIONS(21), 1,
      anon_sym_on,
    ACTIONS(56), 1,
      anon_sym_RBRACE,
    STATE(75), 1,
      sym_global,
    STATE(88), 1,
      sym_type_name,
    STATE(80), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(2), 15,
      sym__statement,
      sym__imperative_statement,
      sym__declarative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_block_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
      sym_on_statement,
      aux_sym_source_file_repeat1,
  [233] = 13,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(19), 1,
      anon_sym_defer,
    ACTIONS(21), 1,
      anon_sym_on,
    STATE(75), 1,
      sym_global,
    STATE(88), 1,
      sym_type_name,
    STATE(80), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(58), 14,
      sym__statement,
      sym__imperative_statement,
      sym__declarative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_block_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
      sym_on_statement,
  [287] = 13,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(19), 1,
      anon_sym_defer,
    ACTIONS(21), 1,
      anon_sym_on,
    STATE(75), 1,
      sym_global,
    STATE(88), 1,
      sym_type_name,
    STATE(80), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(57), 14,
      sym__statement,
      sym__imperative_statement,
      sym__declarative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_block_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
      sym_on_statement,
  [341] = 13,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(19), 1,
      anon_sym_defer,
    ACTIONS(21), 1,
      anon_sym_on,
    STATE(75), 1,
      sym_global,
    STATE(88), 1,
      sym_type_name,
    STATE(80), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(55), 14,
      sym__statement,
      sym__imperative_statement,
      sym__declarative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_block_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
      sym_on_statement,
  [395] = 13,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(58), 1,
      anon_sym_LPAREN,
    ACTIONS(60), 1,
      anon_sym_if,
    ACTIONS(62), 1,
      anon_sym_defer,
    STATE(75), 1,
      sym_global,
    STATE(88), 1,
      sym_type_name,
    STATE(80), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(49), 11,
      sym__imperative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_block_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
  [446] = 13,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(19), 1,
      anon_sym_defer,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    STATE(75), 1,
      sym_global,
    STATE(88), 1,
      sym_type_name,
    STATE(80), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(49), 11,
      sym__imperative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_block_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
  [497] = 12,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(19), 1,
      anon_sym_defer,
    STATE(75), 1,
      sym_global,
    STATE(88), 1,
      sym_type_name,
    STATE(80), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(48), 11,
      sym__imperative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_block_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
  [545] = 12,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(60), 1,
      anon_sym_if,
    ACTIONS(62), 1,
      anon_sym_defer,
    STATE(75), 1,
      sym_global,
    STATE(88), 1,
      sym_type_name,
    STATE(80), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(48), 11,
      sym__imperative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_block_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
  [593] = 12,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(60), 1,
      anon_sym_if,
    ACTIONS(62), 1,
      anon_sym_defer,
    STATE(75), 1,
      sym_global,
    STATE(88), 1,
      sym_type_name,
    STATE(80), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(50), 11,
      sym__imperative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_block_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
  [641] = 12,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(19), 1,
      anon_sym_defer,
    STATE(75), 1,
      sym_global,
    STATE(88), 1,
      sym_type_name,
    STATE(80), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(50), 11,
      sym__imperative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_block_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
  [689] = 12,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(60), 1,
      anon_sym_if,
    ACTIONS(62), 1,
      anon_sym_defer,
    STATE(75), 1,
      sym_global,
    STATE(88), 1,
      sym_type_name,
    STATE(80), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(46), 11,
      sym__imperative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_block_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
  [737] = 12,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(19), 1,
      anon_sym_defer,
    STATE(75), 1,
      sym_global,
    STATE(88), 1,
      sym_type_name,
    STATE(80), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(54), 11,
      sym__imperative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_block_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
  [785] = 12,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(60), 1,
      anon_sym_if,
    ACTIONS(62), 1,
      anon_sym_defer,
    STATE(75), 1,
      sym_global,
    STATE(88), 1,
      sym_type_name,
    STATE(80), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(34), 11,
      sym__imperative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_block_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
  [833] = 11,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(68), 1,
      anon_sym_BANG,
    ACTIONS(70), 1,
      anon_sym_DASH,
    ACTIONS(72), 1,
      anon_sym_RPAREN,
    ACTIONS(76), 1,
      sym_number,
    STATE(62), 1,
      sym_expression,
    STATE(75), 1,
      sym_global,
    ACTIONS(74), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(41), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(40), 4,
      sym_reference,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
  [872] = 11,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(68), 1,
      anon_sym_BANG,
    ACTIONS(70), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      sym_number,
    ACTIONS(78), 1,
      anon_sym_RPAREN,
    STATE(59), 1,
      sym_expression,
    STATE(75), 1,
      sym_global,
    ACTIONS(74), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(41), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(40), 4,
      sym_reference,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
  [911] = 11,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(68), 1,
      anon_sym_BANG,
    ACTIONS(70), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      sym_number,
    ACTIONS(80), 1,
      anon_sym_RPAREN,
    STATE(60), 1,
      sym_expression,
    STATE(75), 1,
      sym_global,
    ACTIONS(74), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(41), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(40), 4,
      sym_reference,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
  [950] = 11,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(68), 1,
      anon_sym_BANG,
    ACTIONS(70), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      sym_number,
    ACTIONS(82), 1,
      anon_sym_RPAREN,
    STATE(64), 1,
      sym_expression,
    STATE(75), 1,
      sym_global,
    ACTIONS(74), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(41), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(40), 4,
      sym_reference,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
  [989] = 10,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(68), 1,
      anon_sym_BANG,
    ACTIONS(70), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      sym_number,
    STATE(61), 1,
      sym_expression,
    STATE(75), 1,
      sym_global,
    ACTIONS(74), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(41), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(40), 4,
      sym_reference,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
  [1025] = 10,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(68), 1,
      anon_sym_BANG,
    ACTIONS(70), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      sym_number,
    STATE(37), 1,
      sym_expression,
    STATE(75), 1,
      sym_global,
    ACTIONS(74), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(41), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(40), 4,
      sym_reference,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
  [1061] = 4,
    ACTIONS(88), 1,
      anon_sym_DOT,
    STATE(24), 1,
      aux_sym__scoped_identifier_repeat1,
    ACTIONS(86), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(84), 11,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      sym_identifier,
  [1085] = 10,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(68), 1,
      anon_sym_BANG,
    ACTIONS(70), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      sym_number,
    STATE(52), 1,
      sym_expression,
    STATE(75), 1,
      sym_global,
    ACTIONS(74), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(41), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(40), 4,
      sym_reference,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
  [1121] = 10,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(68), 1,
      anon_sym_BANG,
    ACTIONS(70), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      sym_number,
    STATE(56), 1,
      sym_expression,
    STATE(75), 1,
      sym_global,
    ACTIONS(74), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(41), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(40), 4,
      sym_reference,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
  [1157] = 4,
    ACTIONS(95), 1,
      anon_sym_DOT,
    STATE(24), 1,
      aux_sym__scoped_identifier_repeat1,
    ACTIONS(93), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(91), 11,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      sym_identifier,
  [1181] = 4,
    ACTIONS(95), 1,
      anon_sym_DOT,
    STATE(27), 1,
      aux_sym__scoped_identifier_repeat1,
    ACTIONS(99), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(97), 11,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      sym_identifier,
  [1205] = 10,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(68), 1,
      anon_sym_BANG,
    ACTIONS(70), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      sym_number,
    STATE(63), 1,
      sym_expression,
    STATE(75), 1,
      sym_global,
    ACTIONS(74), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(41), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(40), 4,
      sym_reference,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
  [1241] = 2,
    ACTIONS(86), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(84), 12,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      sym_identifier,
  [1260] = 2,
    ACTIONS(103), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(101), 11,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      sym_identifier,
  [1278] = 2,
    ACTIONS(105), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(107), 7,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      sym_identifier,
  [1295] = 2,
    ACTIONS(109), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(111), 7,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      sym_identifier,
  [1312] = 3,
    ACTIONS(117), 1,
      anon_sym_else,
    ACTIONS(113), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(115), 6,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      sym_identifier,
  [1331] = 2,
    ACTIONS(119), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(121), 7,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      sym_identifier,
  [1348] = 2,
    ACTIONS(123), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(125), 7,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      sym_identifier,
  [1365] = 2,
    ACTIONS(129), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(127), 10,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [1382] = 2,
    ACTIONS(133), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 10,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [1399] = 2,
    ACTIONS(135), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(137), 7,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      sym_identifier,
  [1416] = 2,
    ACTIONS(141), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(139), 10,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [1433] = 2,
    ACTIONS(145), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(143), 10,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [1450] = 2,
    ACTIONS(147), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(149), 7,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      sym_identifier,
  [1467] = 2,
    ACTIONS(151), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(153), 7,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      sym_identifier,
  [1484] = 2,
    ACTIONS(155), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(157), 7,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      sym_identifier,
  [1501] = 2,
    ACTIONS(159), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(161), 7,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      sym_identifier,
  [1518] = 2,
    ACTIONS(113), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(115), 7,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      sym_identifier,
  [1535] = 2,
    ACTIONS(163), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(165), 7,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      sym_identifier,
  [1552] = 2,
    ACTIONS(167), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(169), 7,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      sym_identifier,
  [1569] = 2,
    ACTIONS(171), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(173), 7,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      sym_identifier,
  [1586] = 2,
    ACTIONS(175), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(177), 7,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      sym_identifier,
  [1603] = 2,
    ACTIONS(179), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(181), 7,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      sym_identifier,
  [1620] = 2,
    ACTIONS(185), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(183), 10,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [1637] = 2,
    ACTIONS(187), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(189), 7,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      sym_identifier,
  [1654] = 2,
    ACTIONS(191), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(193), 7,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      sym_identifier,
  [1671] = 2,
    ACTIONS(195), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(197), 6,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      sym_identifier,
  [1687] = 3,
    ACTIONS(203), 1,
      anon_sym_SEMI,
    ACTIONS(201), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(199), 8,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
  [1705] = 2,
    ACTIONS(205), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(207), 6,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      sym_identifier,
  [1721] = 2,
    ACTIONS(209), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(211), 6,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      sym_identifier,
  [1737] = 3,
    ACTIONS(213), 1,
      anon_sym_RPAREN,
    ACTIONS(201), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(199), 8,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
  [1755] = 3,
    ACTIONS(215), 1,
      anon_sym_RPAREN,
    ACTIONS(201), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(199), 8,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
  [1773] = 3,
    ACTIONS(217), 1,
      anon_sym_RPAREN,
    ACTIONS(201), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(199), 8,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
  [1791] = 3,
    ACTIONS(219), 1,
      anon_sym_RPAREN,
    ACTIONS(201), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(199), 8,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
  [1809] = 3,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
    ACTIONS(201), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(199), 8,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
  [1827] = 3,
    ACTIONS(223), 1,
      anon_sym_RPAREN,
    ACTIONS(201), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(199), 8,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
  [1845] = 5,
    ACTIONS(97), 1,
      sym_identifier,
    ACTIONS(225), 1,
      anon_sym_DOT,
    ACTIONS(227), 1,
      anon_sym_LPAREN,
    ACTIONS(229), 1,
      anon_sym_EQ,
    STATE(27), 1,
      aux_sym__scoped_identifier_repeat1,
  [1861] = 2,
    STATE(84), 1,
      sym_event,
    ACTIONS(231), 3,
      anon_sym_optional,
      anon_sym_inevitable,
      sym_identifier,
  [1870] = 3,
    ACTIONS(233), 1,
      sym_identifier,
    ACTIONS(235), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      sym__trigger_formal,
  [1880] = 2,
    ACTIONS(237), 1,
      anon_sym_LPAREN,
    ACTIONS(84), 2,
      anon_sym_DOT,
      sym_identifier,
  [1888] = 3,
    ACTIONS(239), 1,
      anon_sym_RPAREN,
    ACTIONS(241), 1,
      anon_sym_COMMA,
    STATE(69), 1,
      aux_sym_on_statement_repeat1,
  [1898] = 2,
    ACTIONS(246), 1,
      anon_sym_LT_DASH,
    ACTIONS(244), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1906] = 3,
    ACTIONS(248), 1,
      anon_sym_RPAREN,
    ACTIONS(250), 1,
      anon_sym_COMMA,
    STATE(72), 1,
      aux_sym_on_statement_repeat1,
  [1916] = 3,
    ACTIONS(250), 1,
      anon_sym_COMMA,
    ACTIONS(252), 1,
      anon_sym_RPAREN,
    STATE(69), 1,
      aux_sym_on_statement_repeat1,
  [1926] = 2,
    ACTIONS(233), 1,
      sym_identifier,
    STATE(76), 1,
      sym__trigger_formal,
  [1933] = 2,
    ACTIONS(254), 1,
      sym_identifier,
    ACTIONS(256), 1,
      anon_sym_reply,
  [1940] = 2,
    ACTIONS(258), 1,
      sym_identifier,
    STATE(31), 1,
      sym__scoped_identifier,
  [1947] = 1,
    ACTIONS(260), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1952] = 1,
    ACTIONS(262), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1957] = 1,
    ACTIONS(264), 1,
      anon_sym_SEMI,
  [1961] = 1,
    ACTIONS(266), 1,
      anon_sym_COLON,
  [1965] = 1,
    ACTIONS(268), 1,
      sym_identifier,
  [1969] = 1,
    ACTIONS(270), 1,
      sym_identifier,
  [1973] = 1,
    ACTIONS(272), 1,
      anon_sym_COLON,
  [1977] = 1,
    ACTIONS(274), 1,
      anon_sym_SEMI,
  [1981] = 1,
    ACTIONS(276), 1,
      anon_sym_LPAREN,
  [1985] = 1,
    ACTIONS(278), 1,
      sym_identifier,
  [1989] = 1,
    ACTIONS(280), 1,
      anon_sym_SEMI,
  [1993] = 1,
    ACTIONS(282), 1,
      anon_sym_DOT,
  [1997] = 1,
    ACTIONS(284), 1,
      sym_identifier,
  [2001] = 1,
    ACTIONS(286), 1,
      anon_sym_RPAREN,
  [2005] = 1,
    ACTIONS(288), 1,
      anon_sym_COLON,
  [2009] = 1,
    ACTIONS(290), 1,
      anon_sym_LPAREN,
  [2013] = 1,
    ACTIONS(292), 1,
      sym_identifier,
  [2017] = 1,
    ACTIONS(294), 1,
      ts_builtin_sym_end,
  [2021] = 1,
    ACTIONS(296), 1,
      anon_sym_SEMI,
  [2025] = 1,
    ACTIONS(298), 1,
      anon_sym_SEMI,
  [2029] = 1,
    ACTIONS(300), 1,
      anon_sym_LPAREN,
  [2033] = 1,
    ACTIONS(302), 1,
      anon_sym_SEMI,
  [2037] = 1,
    ACTIONS(304), 1,
      sym_identifier,
  [2041] = 1,
    ACTIONS(306), 1,
      anon_sym_LPAREN,
  [2045] = 1,
    ACTIONS(308), 1,
      anon_sym_SEMI,
  [2049] = 1,
    ACTIONS(310), 1,
      anon_sym_LPAREN,
  [2053] = 1,
    ACTIONS(312), 1,
      anon_sym_SEMI,
  [2057] = 1,
    ACTIONS(314), 1,
      anon_sym_LPAREN,
  [2061] = 1,
    ACTIONS(316), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 59,
  [SMALL_STATE(4)] = 117,
  [SMALL_STATE(5)] = 175,
  [SMALL_STATE(6)] = 233,
  [SMALL_STATE(7)] = 287,
  [SMALL_STATE(8)] = 341,
  [SMALL_STATE(9)] = 395,
  [SMALL_STATE(10)] = 446,
  [SMALL_STATE(11)] = 497,
  [SMALL_STATE(12)] = 545,
  [SMALL_STATE(13)] = 593,
  [SMALL_STATE(14)] = 641,
  [SMALL_STATE(15)] = 689,
  [SMALL_STATE(16)] = 737,
  [SMALL_STATE(17)] = 785,
  [SMALL_STATE(18)] = 833,
  [SMALL_STATE(19)] = 872,
  [SMALL_STATE(20)] = 911,
  [SMALL_STATE(21)] = 950,
  [SMALL_STATE(22)] = 989,
  [SMALL_STATE(23)] = 1025,
  [SMALL_STATE(24)] = 1061,
  [SMALL_STATE(25)] = 1085,
  [SMALL_STATE(26)] = 1121,
  [SMALL_STATE(27)] = 1157,
  [SMALL_STATE(28)] = 1181,
  [SMALL_STATE(29)] = 1205,
  [SMALL_STATE(30)] = 1241,
  [SMALL_STATE(31)] = 1260,
  [SMALL_STATE(32)] = 1278,
  [SMALL_STATE(33)] = 1295,
  [SMALL_STATE(34)] = 1312,
  [SMALL_STATE(35)] = 1331,
  [SMALL_STATE(36)] = 1348,
  [SMALL_STATE(37)] = 1365,
  [SMALL_STATE(38)] = 1382,
  [SMALL_STATE(39)] = 1399,
  [SMALL_STATE(40)] = 1416,
  [SMALL_STATE(41)] = 1433,
  [SMALL_STATE(42)] = 1450,
  [SMALL_STATE(43)] = 1467,
  [SMALL_STATE(44)] = 1484,
  [SMALL_STATE(45)] = 1501,
  [SMALL_STATE(46)] = 1518,
  [SMALL_STATE(47)] = 1535,
  [SMALL_STATE(48)] = 1552,
  [SMALL_STATE(49)] = 1569,
  [SMALL_STATE(50)] = 1586,
  [SMALL_STATE(51)] = 1603,
  [SMALL_STATE(52)] = 1620,
  [SMALL_STATE(53)] = 1637,
  [SMALL_STATE(54)] = 1654,
  [SMALL_STATE(55)] = 1671,
  [SMALL_STATE(56)] = 1687,
  [SMALL_STATE(57)] = 1705,
  [SMALL_STATE(58)] = 1721,
  [SMALL_STATE(59)] = 1737,
  [SMALL_STATE(60)] = 1755,
  [SMALL_STATE(61)] = 1773,
  [SMALL_STATE(62)] = 1791,
  [SMALL_STATE(63)] = 1809,
  [SMALL_STATE(64)] = 1827,
  [SMALL_STATE(65)] = 1845,
  [SMALL_STATE(66)] = 1861,
  [SMALL_STATE(67)] = 1870,
  [SMALL_STATE(68)] = 1880,
  [SMALL_STATE(69)] = 1888,
  [SMALL_STATE(70)] = 1898,
  [SMALL_STATE(71)] = 1906,
  [SMALL_STATE(72)] = 1916,
  [SMALL_STATE(73)] = 1926,
  [SMALL_STATE(74)] = 1933,
  [SMALL_STATE(75)] = 1940,
  [SMALL_STATE(76)] = 1947,
  [SMALL_STATE(77)] = 1952,
  [SMALL_STATE(78)] = 1957,
  [SMALL_STATE(79)] = 1961,
  [SMALL_STATE(80)] = 1965,
  [SMALL_STATE(81)] = 1969,
  [SMALL_STATE(82)] = 1973,
  [SMALL_STATE(83)] = 1977,
  [SMALL_STATE(84)] = 1981,
  [SMALL_STATE(85)] = 1985,
  [SMALL_STATE(86)] = 1989,
  [SMALL_STATE(87)] = 1993,
  [SMALL_STATE(88)] = 1997,
  [SMALL_STATE(89)] = 2001,
  [SMALL_STATE(90)] = 2005,
  [SMALL_STATE(91)] = 2009,
  [SMALL_STATE(92)] = 2013,
  [SMALL_STATE(93)] = 2017,
  [SMALL_STATE(94)] = 2021,
  [SMALL_STATE(95)] = 2025,
  [SMALL_STATE(96)] = 2029,
  [SMALL_STATE(97)] = 2033,
  [SMALL_STATE(98)] = 2037,
  [SMALL_STATE(99)] = 2041,
  [SMALL_STATE(100)] = 2045,
  [SMALL_STATE(101)] = 2049,
  [SMALL_STATE(102)] = 2053,
  [SMALL_STATE(103)] = 2057,
  [SMALL_STATE(104)] = 2061,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(101),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(98),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__scoped_identifier_repeat1, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__scoped_identifier_repeat1, 2, 0, 0),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__scoped_identifier_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__scoped_identifier, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__scoped_identifier, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__scoped_identifier, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__scoped_identifier, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__global_scoped_identifier, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__global_scoped_identifier, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reply_statement, 4, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reply_statement, 4, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_out_event_statement, 6, 0, 7),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_out_event_statement, 6, 0, 7),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, 0, 4),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 5, 0, 4),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_statement, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_statement, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reply_statement, 5, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reply_statement, 5, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_statement, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reference, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reference, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assign_statement, 4, 0, 3),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assign_statement, 4, 0, 3),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_statement, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call_statement, 4, 0, 2),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call_statement, 4, 0, 2),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_illegal_statement, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_illegal_statement, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reply_statement, 6, 0, 6),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reply_statement, 6, 0, 6),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defer_statement, 5, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_defer_statement, 5, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defer_statement, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_defer_statement, 2, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defer_statement, 4, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_defer_statement, 4, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 3, 0, 1),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 3, 0, 1),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reply_statement, 7, 0, 6),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reply_statement, 7, 0, 6),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 7, 0, 8),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 7, 0, 8),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_on_statement, 8, 0, 9),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_on_statement, 8, 0, 9),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_on_statement, 9, 0, 13),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_on_statement, 9, 0, 13),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_on_statement, 10, 0, 14),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_on_statement, 10, 0, 14),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_on_statement_repeat1, 2, 0, 12),
  [241] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_on_statement_repeat1, 2, 0, 12), SHIFT_REPEAT(73),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__trigger_formal, 1, 0, 5),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [254] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [256] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_on_statement_repeat1, 2, 0, 11),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__trigger_formal, 3, 0, 10),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 1, 0, 0),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 1, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_event, 1, 0, 0),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [294] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_dezyne(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
