#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 115
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 69
#define ALIAS_COUNT 0
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 10
#define PRODUCTION_ID_COUNT 16

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_BANG = 2,
  anon_sym_DASH = 3,
  anon_sym_PIPE_PIPE = 4,
  anon_sym_AMP_AMP = 5,
  anon_sym_LT = 6,
  anon_sym_LT_EQ = 7,
  anon_sym_EQ_EQ = 8,
  anon_sym_BANG_EQ = 9,
  anon_sym_GT_EQ = 10,
  anon_sym_GT = 11,
  anon_sym_PLUS = 12,
  anon_sym_DOT = 13,
  anon_sym_reply = 14,
  anon_sym_LPAREN = 15,
  anon_sym_RPAREN = 16,
  anon_sym_SEMI = 17,
  anon_sym_EQ = 18,
  anon_sym_if = 19,
  anon_sym_else = 20,
  anon_sym_LBRACE = 21,
  anon_sym_RBRACE = 22,
  anon_sym_illegal = 23,
  anon_sym_defer = 24,
  anon_sym_on = 25,
  anon_sym_COMMA = 26,
  anon_sym_COLON = 27,
  anon_sym_LBRACK = 28,
  anon_sym_RBRACK = 29,
  sym_otherwise = 30,
  anon_sym_blocking = 31,
  anon_sym_LT_DASH = 32,
  anon_sym_optional = 33,
  anon_sym_inevitable = 34,
  anon_sym_true = 35,
  anon_sym_false = 36,
  sym_number = 37,
  sym_source_file = 38,
  sym_expression = 39,
  sym_reference = 40,
  sym_unary_expression = 41,
  sym_binary_expression = 42,
  sym__statement = 43,
  sym__imperative_statement = 44,
  sym__declarative_statement = 45,
  sym_reply_statement = 46,
  sym_variable_declaration = 47,
  sym_assign_statement = 48,
  sym_if_statement = 49,
  sym_empty_statement = 50,
  sym_compound_statement = 51,
  sym_function_call_statement = 52,
  sym_out_event_statement = 53,
  sym_illegal_statement = 54,
  sym_defer_statement = 55,
  sym_on_statement = 56,
  sym_guard_statement = 57,
  sym_blocking_statement = 58,
  sym__trigger_formal = 59,
  sym_event = 60,
  sym_type_name = 61,
  sym__scoped_identifier = 62,
  sym__global_scoped_identifier = 63,
  sym_global = 64,
  sym_literal = 65,
  aux_sym_source_file_repeat1 = 66,
  aux_sym_on_statement_repeat1 = 67,
  aux_sym__scoped_identifier_repeat1 = 68,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_BANG] = "!",
  [anon_sym_DASH] = "-",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_GT] = ">",
  [anon_sym_PLUS] = "+",
  [anon_sym_DOT] = ".",
  [anon_sym_reply] = "reply",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_SEMI] = ";",
  [anon_sym_EQ] = "=",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_illegal] = "illegal",
  [anon_sym_defer] = "defer",
  [anon_sym_on] = "on",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_otherwise] = "otherwise",
  [anon_sym_blocking] = "blocking",
  [anon_sym_LT_DASH] = "<-",
  [anon_sym_optional] = "optional",
  [anon_sym_inevitable] = "inevitable",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [sym_expression] = "expression",
  [sym_reference] = "reference",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym__statement] = "_statement",
  [sym__imperative_statement] = "_imperative_statement",
  [sym__declarative_statement] = "_declarative_statement",
  [sym_reply_statement] = "reply_statement",
  [sym_variable_declaration] = "variable_declaration",
  [sym_assign_statement] = "assign_statement",
  [sym_if_statement] = "if_statement",
  [sym_empty_statement] = "empty_statement",
  [sym_compound_statement] = "compound_statement",
  [sym_function_call_statement] = "function_call_statement",
  [sym_out_event_statement] = "out_event_statement",
  [sym_illegal_statement] = "illegal_statement",
  [sym_defer_statement] = "defer_statement",
  [sym_on_statement] = "on_statement",
  [sym_guard_statement] = "guard_statement",
  [sym_blocking_statement] = "blocking_statement",
  [sym__trigger_formal] = "_trigger_formal",
  [sym_event] = "event",
  [sym_type_name] = "type_name",
  [sym__scoped_identifier] = "_scoped_identifier",
  [sym__global_scoped_identifier] = "_global_scoped_identifier",
  [sym_global] = "global",
  [sym_literal] = "literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_on_statement_repeat1] = "on_statement_repeat1",
  [aux_sym__scoped_identifier_repeat1] = "_scoped_identifier_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_reply] = anon_sym_reply,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_illegal] = anon_sym_illegal,
  [anon_sym_defer] = anon_sym_defer,
  [anon_sym_on] = anon_sym_on,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_otherwise] = sym_otherwise,
  [anon_sym_blocking] = anon_sym_blocking,
  [anon_sym_LT_DASH] = anon_sym_LT_DASH,
  [anon_sym_optional] = anon_sym_optional,
  [anon_sym_inevitable] = anon_sym_inevitable,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [sym_expression] = sym_expression,
  [sym_reference] = sym_reference,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym__statement] = sym__statement,
  [sym__imperative_statement] = sym__imperative_statement,
  [sym__declarative_statement] = sym__declarative_statement,
  [sym_reply_statement] = sym_reply_statement,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_assign_statement] = sym_assign_statement,
  [sym_if_statement] = sym_if_statement,
  [sym_empty_statement] = sym_empty_statement,
  [sym_compound_statement] = sym_compound_statement,
  [sym_function_call_statement] = sym_function_call_statement,
  [sym_out_event_statement] = sym_out_event_statement,
  [sym_illegal_statement] = sym_illegal_statement,
  [sym_defer_statement] = sym_defer_statement,
  [sym_on_statement] = sym_on_statement,
  [sym_guard_statement] = sym_guard_statement,
  [sym_blocking_statement] = sym_blocking_statement,
  [sym__trigger_formal] = sym__trigger_formal,
  [sym_event] = sym_event,
  [sym_type_name] = sym_type_name,
  [sym__scoped_identifier] = sym__scoped_identifier,
  [sym__global_scoped_identifier] = sym__global_scoped_identifier,
  [sym_global] = sym_global,
  [sym_literal] = sym_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_on_statement_repeat1] = aux_sym_on_statement_repeat1,
  [aux_sym__scoped_identifier_repeat1] = aux_sym__scoped_identifier_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_reply] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_illegal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_defer] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_on] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_otherwise] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_blocking] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_optional] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_inevitable] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__imperative_statement] = {
    .visible = false,
    .named = true,
  },
  [sym__declarative_statement] = {
    .visible = false,
    .named = true,
  },
  [sym_reply_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_assign_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_empty_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_compound_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_out_event_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_illegal_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_defer_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_on_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_guard_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_blocking_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__trigger_formal] = {
    .visible = false,
    .named = true,
  },
  [sym_event] = {
    .visible = true,
    .named = true,
  },
  [sym_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym__scoped_identifier] = {
    .visible = false,
    .named = true,
  },
  [sym__global_scoped_identifier] = {
    .visible = false,
    .named = true,
  },
  [sym_global] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_on_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__scoped_identifier_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_event = 1,
  field_expression = 2,
  field_false = 3,
  field_function = 4,
  field_init = 5,
  field_port = 6,
  field_ref = 7,
  field_true = 8,
  field_type = 9,
  field_var = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_event] = "event",
  [field_expression] = "expression",
  [field_false] = "false",
  [field_function] = "function",
  [field_init] = "init",
  [field_port] = "port",
  [field_ref] = "ref",
  [field_true] = "true",
  [field_type] = "type",
  [field_var] = "var",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 3},
  [6] = {.index = 10, .length = 1},
  [7] = {.index = 11, .length = 1},
  [8] = {.index = 12, .length = 2},
  [9] = {.index = 14, .length = 3},
  [10] = {.index = 17, .length = 2},
  [11] = {.index = 19, .length = 2},
  [12] = {.index = 21, .length = 2},
  [13] = {.index = 23, .length = 4},
  [14] = {.index = 27, .length = 4},
  [15] = {.index = 31, .length = 6},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_type, 0},
    {field_var, 1},
  [2] =
    {field_function, 0},
  [3] =
    {field_expression, 2},
    {field_var, 0},
  [5] =
    {field_expression, 2},
    {field_true, 4},
  [7] =
    {field_init, 3},
    {field_type, 0},
    {field_var, 1},
  [10] =
    {field_var, 0},
  [11] =
    {field_port, 0},
  [12] =
    {field_event, 2},
    {field_port, 0},
  [14] =
    {field_expression, 2},
    {field_false, 6},
    {field_true, 4},
  [17] =
    {field_event, 3},
    {field_port, 1},
  [19] =
    {field_ref, 2},
    {field_var, 0},
  [21] =
    {field_ref, 1, .inherited = true},
    {field_var, 1, .inherited = true},
  [23] =
    {field_ref, 0, .inherited = true},
    {field_ref, 1, .inherited = true},
    {field_var, 0, .inherited = true},
    {field_var, 1, .inherited = true},
  [27] =
    {field_event, 3},
    {field_port, 1},
    {field_ref, 5, .inherited = true},
    {field_var, 5, .inherited = true},
  [31] =
    {field_event, 3},
    {field_port, 1},
    {field_ref, 5, .inherited = true},
    {field_ref, 6, .inherited = true},
    {field_var, 5, .inherited = true},
    {field_var, 6, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 11,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 14,
  [17] = 13,
  [18] = 15,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 20,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 30,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 35,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 66,
  [70] = 67,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 109,
  [113] = 113,
  [114] = 114,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '!', 10,
        '&', 3,
        '(', 23,
        ')', 24,
        '+', 21,
        ',', 30,
        '-', 12,
        '.', 22,
        ':', 31,
        ';', 25,
        '<', 15,
        '=', 27,
        '>', 20,
        '[', 32,
        ']', 33,
        '{', 28,
        '|', 7,
        '}', 29,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 9,
        '(', 23,
        ')', 24,
        ',', 30,
        '-', 12,
        '.', 22,
        ';', 25,
        '<', 4,
        '=', 26,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '!', 5,
        '&', 3,
        ')', 24,
        '+', 21,
        '-', 11,
        '.', 22,
        ';', 25,
        '<', 15,
        '=', 6,
        '>', 20,
        ']', 33,
        '|', 7,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 3:
      if (lookahead == '&') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(34);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(18);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == '|') ADVANCE(13);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(18);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(19);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(17);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LT_DASH);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'b', 1,
        'd', 2,
        'e', 3,
        'f', 4,
        'i', 5,
        'o', 6,
        'r', 7,
        't', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(12);
      END_STATE();
    case 5:
      if (lookahead == 'f') ADVANCE(13);
      if (lookahead == 'l') ADVANCE(14);
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(16);
      if (lookahead == 'p') ADVANCE(17);
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == 'f') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == 's') ADVANCE(23);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(24);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_on);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 18:
      if (lookahead == 'h') ADVANCE(28);
      END_STATE();
    case 19:
      if (lookahead == 'p') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'u') ADVANCE(30);
      END_STATE();
    case 21:
      if (lookahead == 'c') ADVANCE(31);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(34);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 26:
      if (lookahead == 'v') ADVANCE(36);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(37);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 29:
      if (lookahead == 'l') ADVANCE(39);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 31:
      if (lookahead == 'k') ADVANCE(41);
      END_STATE();
    case 32:
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 35:
      if (lookahead == 'g') ADVANCE(44);
      END_STATE();
    case 36:
      if (lookahead == 'i') ADVANCE(45);
      END_STATE();
    case 37:
      if (lookahead == 'o') ADVANCE(46);
      END_STATE();
    case 38:
      if (lookahead == 'r') ADVANCE(47);
      END_STATE();
    case 39:
      if (lookahead == 'y') ADVANCE(48);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 41:
      if (lookahead == 'i') ADVANCE(49);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_defer);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 44:
      if (lookahead == 'a') ADVANCE(50);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(51);
      END_STATE();
    case 46:
      if (lookahead == 'n') ADVANCE(52);
      END_STATE();
    case 47:
      if (lookahead == 'w') ADVANCE(53);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_reply);
      END_STATE();
    case 49:
      if (lookahead == 'n') ADVANCE(54);
      END_STATE();
    case 50:
      if (lookahead == 'l') ADVANCE(55);
      END_STATE();
    case 51:
      if (lookahead == 'a') ADVANCE(56);
      END_STATE();
    case 52:
      if (lookahead == 'a') ADVANCE(57);
      END_STATE();
    case 53:
      if (lookahead == 'i') ADVANCE(58);
      END_STATE();
    case 54:
      if (lookahead == 'g') ADVANCE(59);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_illegal);
      END_STATE();
    case 56:
      if (lookahead == 'b') ADVANCE(60);
      END_STATE();
    case 57:
      if (lookahead == 'l') ADVANCE(61);
      END_STATE();
    case 58:
      if (lookahead == 's') ADVANCE(62);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_blocking);
      END_STATE();
    case 60:
      if (lookahead == 'l') ADVANCE(63);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_optional);
      END_STATE();
    case 62:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 63:
      if (lookahead == 'e') ADVANCE(65);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_otherwise);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_inevitable);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 2},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_reply] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_illegal] = ACTIONS(1),
    [anon_sym_defer] = ACTIONS(1),
    [anon_sym_on] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_otherwise] = ACTIONS(1),
    [anon_sym_blocking] = ACTIONS(1),
    [anon_sym_optional] = ACTIONS(1),
    [anon_sym_inevitable] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(106),
    [sym__statement] = STATE(5),
    [sym__imperative_statement] = STATE(5),
    [sym__declarative_statement] = STATE(5),
    [sym_reply_statement] = STATE(5),
    [sym_variable_declaration] = STATE(5),
    [sym_assign_statement] = STATE(5),
    [sym_if_statement] = STATE(5),
    [sym_empty_statement] = STATE(5),
    [sym_compound_statement] = STATE(5),
    [sym_function_call_statement] = STATE(5),
    [sym_out_event_statement] = STATE(5),
    [sym_illegal_statement] = STATE(5),
    [sym_defer_statement] = STATE(5),
    [sym_on_statement] = STATE(5),
    [sym_guard_statement] = STATE(5),
    [sym_blocking_statement] = STATE(5),
    [sym_type_name] = STATE(105),
    [sym__scoped_identifier] = STATE(103),
    [sym__global_scoped_identifier] = STATE(103),
    [sym_global] = STATE(84),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_DOT] = ACTIONS(7),
    [anon_sym_reply] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_illegal] = ACTIONS(17),
    [anon_sym_defer] = ACTIONS(19),
    [anon_sym_on] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_blocking] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(32), 1,
      anon_sym_DOT,
    ACTIONS(35), 1,
      anon_sym_reply,
    ACTIONS(38), 1,
      anon_sym_SEMI,
    ACTIONS(41), 1,
      anon_sym_if,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_illegal,
    ACTIONS(50), 1,
      anon_sym_defer,
    ACTIONS(53), 1,
      anon_sym_on,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_blocking,
    STATE(84), 1,
      sym_global,
    STATE(105), 1,
      sym_type_name,
    ACTIONS(27), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(103), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(2), 17,
      sym__statement,
      sym__imperative_statement,
      sym__declarative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_compound_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
      sym_on_statement,
      sym_guard_statement,
      sym_blocking_statement,
      aux_sym_source_file_repeat1,
  [67] = 16,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(19), 1,
      anon_sym_defer,
    ACTIONS(21), 1,
      anon_sym_on,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_blocking,
    ACTIONS(62), 1,
      anon_sym_RBRACE,
    STATE(84), 1,
      sym_global,
    STATE(105), 1,
      sym_type_name,
    STATE(103), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(4), 17,
      sym__statement,
      sym__imperative_statement,
      sym__declarative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_compound_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
      sym_on_statement,
      sym_guard_statement,
      sym_blocking_statement,
      aux_sym_source_file_repeat1,
  [133] = 16,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(19), 1,
      anon_sym_defer,
    ACTIONS(21), 1,
      anon_sym_on,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_blocking,
    ACTIONS(64), 1,
      anon_sym_RBRACE,
    STATE(84), 1,
      sym_global,
    STATE(105), 1,
      sym_type_name,
    STATE(103), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(2), 17,
      sym__statement,
      sym__imperative_statement,
      sym__declarative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_compound_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
      sym_on_statement,
      sym_guard_statement,
      sym_blocking_statement,
      aux_sym_source_file_repeat1,
  [199] = 16,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(19), 1,
      anon_sym_defer,
    ACTIONS(21), 1,
      anon_sym_on,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_blocking,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    STATE(84), 1,
      sym_global,
    STATE(105), 1,
      sym_type_name,
    STATE(103), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(2), 17,
      sym__statement,
      sym__imperative_statement,
      sym__declarative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_compound_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
      sym_on_statement,
      sym_guard_statement,
      sym_blocking_statement,
      aux_sym_source_file_repeat1,
  [265] = 15,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(19), 1,
      anon_sym_defer,
    ACTIONS(21), 1,
      anon_sym_on,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_blocking,
    STATE(84), 1,
      sym_global,
    STATE(105), 1,
      sym_type_name,
    STATE(103), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(57), 16,
      sym__statement,
      sym__imperative_statement,
      sym__declarative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_compound_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
      sym_on_statement,
      sym_guard_statement,
      sym_blocking_statement,
  [327] = 15,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(19), 1,
      anon_sym_defer,
    ACTIONS(21), 1,
      anon_sym_on,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_blocking,
    STATE(84), 1,
      sym_global,
    STATE(105), 1,
      sym_type_name,
    STATE(103), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(61), 16,
      sym__statement,
      sym__imperative_statement,
      sym__declarative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_compound_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
      sym_on_statement,
      sym_guard_statement,
      sym_blocking_statement,
  [389] = 15,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(19), 1,
      anon_sym_defer,
    ACTIONS(21), 1,
      anon_sym_on,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_blocking,
    STATE(84), 1,
      sym_global,
    STATE(105), 1,
      sym_type_name,
    STATE(103), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(60), 16,
      sym__statement,
      sym__imperative_statement,
      sym__declarative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_compound_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
      sym_on_statement,
      sym_guard_statement,
      sym_blocking_statement,
  [451] = 15,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(19), 1,
      anon_sym_defer,
    ACTIONS(21), 1,
      anon_sym_on,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_blocking,
    STATE(84), 1,
      sym_global,
    STATE(105), 1,
      sym_type_name,
    STATE(103), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(56), 16,
      sym__statement,
      sym__imperative_statement,
      sym__declarative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_compound_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
      sym_on_statement,
      sym_guard_statement,
      sym_blocking_statement,
  [513] = 15,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(19), 1,
      anon_sym_defer,
    ACTIONS(21), 1,
      anon_sym_on,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_blocking,
    STATE(84), 1,
      sym_global,
    STATE(105), 1,
      sym_type_name,
    STATE(103), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(58), 16,
      sym__statement,
      sym__imperative_statement,
      sym__declarative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_compound_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
      sym_on_statement,
      sym_guard_statement,
      sym_blocking_statement,
  [575] = 13,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(19), 1,
      anon_sym_defer,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    STATE(84), 1,
      sym_global,
    STATE(105), 1,
      sym_type_name,
    STATE(103), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(40), 11,
      sym__imperative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_compound_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
  [626] = 13,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      anon_sym_defer,
    STATE(84), 1,
      sym_global,
    STATE(105), 1,
      sym_type_name,
    STATE(103), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(40), 11,
      sym__imperative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_compound_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
  [677] = 12,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      anon_sym_defer,
    STATE(84), 1,
      sym_global,
    STATE(105), 1,
      sym_type_name,
    STATE(103), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(48), 11,
      sym__imperative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_compound_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
  [725] = 12,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      anon_sym_defer,
    STATE(84), 1,
      sym_global,
    STATE(105), 1,
      sym_type_name,
    STATE(103), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(50), 11,
      sym__imperative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_compound_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
  [773] = 12,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(19), 1,
      anon_sym_defer,
    STATE(84), 1,
      sym_global,
    STATE(105), 1,
      sym_type_name,
    STATE(103), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(47), 11,
      sym__imperative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_compound_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
  [821] = 12,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      anon_sym_defer,
    STATE(84), 1,
      sym_global,
    STATE(105), 1,
      sym_type_name,
    STATE(103), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(35), 11,
      sym__imperative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_compound_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
  [869] = 12,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(19), 1,
      anon_sym_defer,
    STATE(84), 1,
      sym_global,
    STATE(105), 1,
      sym_type_name,
    STATE(103), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(48), 11,
      sym__imperative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_compound_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
  [917] = 12,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(72), 1,
      anon_sym_if,
    ACTIONS(74), 1,
      anon_sym_defer,
    STATE(84), 1,
      sym_global,
    STATE(105), 1,
      sym_type_name,
    STATE(103), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(47), 11,
      sym__imperative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_compound_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
  [965] = 12,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      anon_sym_reply,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_illegal,
    ACTIONS(19), 1,
      anon_sym_defer,
    STATE(84), 1,
      sym_global,
    STATE(105), 1,
      sym_type_name,
    STATE(103), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(53), 11,
      sym__imperative_statement,
      sym_reply_statement,
      sym_variable_declaration,
      sym_assign_statement,
      sym_if_statement,
      sym_empty_statement,
      sym_compound_statement,
      sym_function_call_statement,
      sym_out_event_statement,
      sym_illegal_statement,
      sym_defer_statement,
  [1013] = 11,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(76), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_BANG,
    ACTIONS(80), 1,
      anon_sym_DASH,
    ACTIONS(82), 1,
      anon_sym_RPAREN,
    ACTIONS(86), 1,
      sym_number,
    STATE(66), 1,
      sym_expression,
    STATE(84), 1,
      sym_global,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(64), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(63), 4,
      sym_reference,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
  [1052] = 11,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(76), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_BANG,
    ACTIONS(80), 1,
      anon_sym_DASH,
    ACTIONS(86), 1,
      sym_number,
    ACTIONS(88), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      sym_expression,
    STATE(84), 1,
      sym_global,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(64), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(63), 4,
      sym_reference,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
  [1091] = 11,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(76), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_BANG,
    ACTIONS(80), 1,
      anon_sym_DASH,
    ACTIONS(86), 1,
      sym_number,
    ACTIONS(90), 1,
      anon_sym_RPAREN,
    STATE(73), 1,
      sym_expression,
    STATE(84), 1,
      sym_global,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(64), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(63), 4,
      sym_reference,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
  [1130] = 4,
    ACTIONS(96), 1,
      anon_sym_DOT,
    STATE(23), 1,
      aux_sym__scoped_identifier_repeat1,
    ACTIONS(94), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(92), 12,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      sym_identifier,
  [1155] = 11,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(76), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_BANG,
    ACTIONS(80), 1,
      anon_sym_DASH,
    ACTIONS(86), 1,
      sym_number,
    ACTIONS(99), 1,
      anon_sym_RPAREN,
    STATE(69), 1,
      sym_expression,
    STATE(84), 1,
      sym_global,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(64), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(63), 4,
      sym_reference,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
  [1194] = 4,
    ACTIONS(105), 1,
      anon_sym_DOT,
    STATE(23), 1,
      aux_sym__scoped_identifier_repeat1,
    ACTIONS(103), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(101), 12,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      sym_identifier,
  [1219] = 11,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(76), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_BANG,
    ACTIONS(80), 1,
      anon_sym_DASH,
    ACTIONS(86), 1,
      sym_number,
    ACTIONS(107), 1,
      sym_otherwise,
    STATE(68), 1,
      sym_expression,
    STATE(84), 1,
      sym_global,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(64), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(63), 4,
      sym_reference,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
  [1258] = 4,
    ACTIONS(105), 1,
      anon_sym_DOT,
    STATE(25), 1,
      aux_sym__scoped_identifier_repeat1,
    ACTIONS(111), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(109), 12,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      sym_identifier,
  [1283] = 10,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(76), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_BANG,
    ACTIONS(80), 1,
      anon_sym_DASH,
    ACTIONS(86), 1,
      sym_number,
    STATE(59), 1,
      sym_expression,
    STATE(84), 1,
      sym_global,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(64), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(63), 4,
      sym_reference,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
  [1319] = 10,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(76), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_BANG,
    ACTIONS(80), 1,
      anon_sym_DASH,
    ACTIONS(86), 1,
      sym_number,
    STATE(65), 1,
      sym_expression,
    STATE(84), 1,
      sym_global,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(64), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(63), 4,
      sym_reference,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
  [1355] = 10,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(76), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_BANG,
    ACTIONS(80), 1,
      anon_sym_DASH,
    ACTIONS(86), 1,
      sym_number,
    STATE(67), 1,
      sym_expression,
    STATE(84), 1,
      sym_global,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(64), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(63), 4,
      sym_reference,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
  [1391] = 10,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(76), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_BANG,
    ACTIONS(80), 1,
      anon_sym_DASH,
    ACTIONS(86), 1,
      sym_number,
    STATE(72), 1,
      sym_expression,
    STATE(84), 1,
      sym_global,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(64), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(63), 4,
      sym_reference,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
  [1427] = 10,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(76), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_BANG,
    ACTIONS(80), 1,
      anon_sym_DASH,
    ACTIONS(86), 1,
      sym_number,
    STATE(62), 1,
      sym_expression,
    STATE(84), 1,
      sym_global,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(64), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(63), 4,
      sym_reference,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
  [1463] = 10,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(76), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_BANG,
    ACTIONS(80), 1,
      anon_sym_DASH,
    ACTIONS(86), 1,
      sym_number,
    STATE(70), 1,
      sym_expression,
    STATE(84), 1,
      sym_global,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(64), 2,
      sym__scoped_identifier,
      sym__global_scoped_identifier,
    STATE(63), 4,
      sym_reference,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
  [1499] = 2,
    ACTIONS(94), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(92), 13,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      sym_identifier,
  [1519] = 3,
    ACTIONS(117), 1,
      anon_sym_else,
    ACTIONS(113), 6,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(115), 7,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      anon_sym_blocking,
      sym_identifier,
  [1540] = 2,
    ACTIONS(119), 6,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(121), 8,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      anon_sym_blocking,
      sym_identifier,
  [1559] = 2,
    ACTIONS(123), 6,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(125), 8,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      anon_sym_blocking,
      sym_identifier,
  [1578] = 2,
    ACTIONS(127), 6,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(129), 8,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      anon_sym_blocking,
      sym_identifier,
  [1597] = 2,
    ACTIONS(133), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 12,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      sym_identifier,
  [1616] = 2,
    ACTIONS(135), 6,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(137), 8,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      anon_sym_blocking,
      sym_identifier,
  [1635] = 2,
    ACTIONS(139), 6,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(141), 8,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      anon_sym_blocking,
      sym_identifier,
  [1654] = 2,
    ACTIONS(143), 6,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(145), 8,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      anon_sym_blocking,
      sym_identifier,
  [1673] = 2,
    ACTIONS(147), 6,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(149), 8,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      anon_sym_blocking,
      sym_identifier,
  [1692] = 2,
    ACTIONS(151), 6,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(153), 8,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      anon_sym_blocking,
      sym_identifier,
  [1711] = 2,
    ACTIONS(155), 6,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(157), 8,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      anon_sym_blocking,
      sym_identifier,
  [1730] = 2,
    ACTIONS(159), 6,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(161), 8,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      anon_sym_blocking,
      sym_identifier,
  [1749] = 2,
    ACTIONS(163), 6,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(165), 8,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      anon_sym_blocking,
      sym_identifier,
  [1768] = 2,
    ACTIONS(167), 6,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(169), 8,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      anon_sym_blocking,
      sym_identifier,
  [1787] = 2,
    ACTIONS(171), 6,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(173), 8,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      anon_sym_blocking,
      sym_identifier,
  [1806] = 2,
    ACTIONS(113), 6,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(115), 8,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      anon_sym_blocking,
      sym_identifier,
  [1825] = 2,
    ACTIONS(175), 6,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(177), 8,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      anon_sym_blocking,
      sym_identifier,
  [1844] = 2,
    ACTIONS(179), 6,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(181), 8,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      anon_sym_blocking,
      sym_identifier,
  [1863] = 2,
    ACTIONS(183), 6,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(185), 8,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      anon_sym_blocking,
      sym_identifier,
  [1882] = 2,
    ACTIONS(187), 6,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(189), 8,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_else,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      anon_sym_blocking,
      sym_identifier,
  [1901] = 2,
    ACTIONS(193), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(191), 11,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [1919] = 2,
    ACTIONS(195), 6,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(197), 7,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      anon_sym_blocking,
      sym_identifier,
  [1937] = 2,
    ACTIONS(199), 6,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(201), 7,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      anon_sym_blocking,
      sym_identifier,
  [1955] = 2,
    ACTIONS(203), 6,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(205), 7,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      anon_sym_blocking,
      sym_identifier,
  [1973] = 2,
    ACTIONS(209), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(207), 11,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [1991] = 2,
    ACTIONS(211), 6,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(213), 7,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      anon_sym_blocking,
      sym_identifier,
  [2009] = 2,
    ACTIONS(215), 6,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(217), 7,
      anon_sym_reply,
      anon_sym_if,
      anon_sym_illegal,
      anon_sym_defer,
      anon_sym_on,
      anon_sym_blocking,
      sym_identifier,
  [2027] = 2,
    ACTIONS(221), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(219), 11,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [2045] = 2,
    ACTIONS(225), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(223), 11,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [2063] = 2,
    ACTIONS(229), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(227), 11,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [2081] = 3,
    ACTIONS(235), 1,
      anon_sym_SEMI,
    ACTIONS(233), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(231), 8,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
  [2099] = 3,
    ACTIONS(237), 1,
      anon_sym_RPAREN,
    ACTIONS(233), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(231), 8,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
  [2117] = 3,
    ACTIONS(239), 1,
      anon_sym_RPAREN,
    ACTIONS(233), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(231), 8,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
  [2135] = 3,
    ACTIONS(241), 1,
      anon_sym_RBRACK,
    ACTIONS(233), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(231), 8,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
  [2153] = 3,
    ACTIONS(243), 1,
      anon_sym_RPAREN,
    ACTIONS(233), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(231), 8,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
  [2171] = 3,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
    ACTIONS(233), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(231), 8,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
  [2189] = 3,
    ACTIONS(247), 1,
      anon_sym_RPAREN,
    ACTIONS(233), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(231), 8,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
  [2207] = 3,
    ACTIONS(249), 1,
      anon_sym_SEMI,
    ACTIONS(233), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(231), 8,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
  [2225] = 3,
    ACTIONS(251), 1,
      anon_sym_RPAREN,
    ACTIONS(233), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(231), 8,
      anon_sym_DASH,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
  [2243] = 5,
    ACTIONS(109), 1,
      sym_identifier,
    ACTIONS(253), 1,
      anon_sym_DOT,
    ACTIONS(255), 1,
      anon_sym_LPAREN,
    ACTIONS(257), 1,
      anon_sym_EQ,
    STATE(25), 1,
      aux_sym__scoped_identifier_repeat1,
  [2259] = 2,
    STATE(96), 1,
      sym_event,
    ACTIONS(259), 3,
      anon_sym_optional,
      anon_sym_inevitable,
      sym_identifier,
  [2268] = 3,
    ACTIONS(261), 1,
      anon_sym_RPAREN,
    ACTIONS(263), 1,
      anon_sym_COMMA,
    STATE(77), 1,
      aux_sym_on_statement_repeat1,
  [2278] = 3,
    ACTIONS(263), 1,
      anon_sym_COMMA,
    ACTIONS(265), 1,
      anon_sym_RPAREN,
    STATE(80), 1,
      aux_sym_on_statement_repeat1,
  [2288] = 2,
    ACTIONS(267), 1,
      anon_sym_LPAREN,
    ACTIONS(92), 2,
      anon_sym_DOT,
      sym_identifier,
  [2296] = 3,
    ACTIONS(269), 1,
      sym_identifier,
    ACTIONS(271), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      sym__trigger_formal,
  [2306] = 3,
    ACTIONS(273), 1,
      anon_sym_RPAREN,
    ACTIONS(275), 1,
      anon_sym_COMMA,
    STATE(80), 1,
      aux_sym_on_statement_repeat1,
  [2316] = 2,
    ACTIONS(280), 1,
      anon_sym_LT_DASH,
    ACTIONS(278), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2324] = 1,
    ACTIONS(282), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2329] = 2,
    ACTIONS(284), 1,
      sym_identifier,
    ACTIONS(286), 1,
      anon_sym_reply,
  [2336] = 2,
    ACTIONS(288), 1,
      sym_identifier,
    STATE(39), 1,
      sym__scoped_identifier,
  [2343] = 1,
    ACTIONS(290), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2348] = 2,
    ACTIONS(292), 1,
      anon_sym_SEMI,
    ACTIONS(294), 1,
      anon_sym_EQ,
  [2355] = 2,
    ACTIONS(269), 1,
      sym_identifier,
    STATE(82), 1,
      sym__trigger_formal,
  [2362] = 1,
    ACTIONS(296), 1,
      anon_sym_DOT,
  [2366] = 1,
    ACTIONS(298), 1,
      anon_sym_SEMI,
  [2370] = 1,
    ACTIONS(300), 1,
      anon_sym_SEMI,
  [2374] = 1,
    ACTIONS(302), 1,
      anon_sym_SEMI,
  [2378] = 1,
    ACTIONS(304), 1,
      anon_sym_RPAREN,
  [2382] = 1,
    ACTIONS(241), 1,
      anon_sym_RBRACK,
  [2386] = 1,
    ACTIONS(306), 1,
      sym_identifier,
  [2390] = 1,
    ACTIONS(308), 1,
      anon_sym_COLON,
  [2394] = 1,
    ACTIONS(310), 1,
      anon_sym_LPAREN,
  [2398] = 1,
    ACTIONS(312), 1,
      anon_sym_RPAREN,
  [2402] = 1,
    ACTIONS(314), 1,
      anon_sym_SEMI,
  [2406] = 1,
    ACTIONS(316), 1,
      anon_sym_COLON,
  [2410] = 1,
    ACTIONS(318), 1,
      anon_sym_COLON,
  [2414] = 1,
    ACTIONS(320), 1,
      sym_identifier,
  [2418] = 1,
    ACTIONS(322), 1,
      anon_sym_LPAREN,
  [2422] = 1,
    ACTIONS(324), 1,
      sym_identifier,
  [2426] = 1,
    ACTIONS(326), 1,
      sym_identifier,
  [2430] = 1,
    ACTIONS(328), 1,
      sym_identifier,
  [2434] = 1,
    ACTIONS(330), 1,
      ts_builtin_sym_end,
  [2438] = 1,
    ACTIONS(332), 1,
      anon_sym_LPAREN,
  [2442] = 1,
    ACTIONS(334), 1,
      anon_sym_SEMI,
  [2446] = 1,
    ACTIONS(336), 1,
      anon_sym_LPAREN,
  [2450] = 1,
    ACTIONS(338), 1,
      sym_identifier,
  [2454] = 1,
    ACTIONS(340), 1,
      anon_sym_SEMI,
  [2458] = 1,
    ACTIONS(342), 1,
      anon_sym_LPAREN,
  [2462] = 1,
    ACTIONS(344), 1,
      anon_sym_LPAREN,
  [2466] = 1,
    ACTIONS(346), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 67,
  [SMALL_STATE(4)] = 133,
  [SMALL_STATE(5)] = 199,
  [SMALL_STATE(6)] = 265,
  [SMALL_STATE(7)] = 327,
  [SMALL_STATE(8)] = 389,
  [SMALL_STATE(9)] = 451,
  [SMALL_STATE(10)] = 513,
  [SMALL_STATE(11)] = 575,
  [SMALL_STATE(12)] = 626,
  [SMALL_STATE(13)] = 677,
  [SMALL_STATE(14)] = 725,
  [SMALL_STATE(15)] = 773,
  [SMALL_STATE(16)] = 821,
  [SMALL_STATE(17)] = 869,
  [SMALL_STATE(18)] = 917,
  [SMALL_STATE(19)] = 965,
  [SMALL_STATE(20)] = 1013,
  [SMALL_STATE(21)] = 1052,
  [SMALL_STATE(22)] = 1091,
  [SMALL_STATE(23)] = 1130,
  [SMALL_STATE(24)] = 1155,
  [SMALL_STATE(25)] = 1194,
  [SMALL_STATE(26)] = 1219,
  [SMALL_STATE(27)] = 1258,
  [SMALL_STATE(28)] = 1283,
  [SMALL_STATE(29)] = 1319,
  [SMALL_STATE(30)] = 1355,
  [SMALL_STATE(31)] = 1391,
  [SMALL_STATE(32)] = 1427,
  [SMALL_STATE(33)] = 1463,
  [SMALL_STATE(34)] = 1499,
  [SMALL_STATE(35)] = 1519,
  [SMALL_STATE(36)] = 1540,
  [SMALL_STATE(37)] = 1559,
  [SMALL_STATE(38)] = 1578,
  [SMALL_STATE(39)] = 1597,
  [SMALL_STATE(40)] = 1616,
  [SMALL_STATE(41)] = 1635,
  [SMALL_STATE(42)] = 1654,
  [SMALL_STATE(43)] = 1673,
  [SMALL_STATE(44)] = 1692,
  [SMALL_STATE(45)] = 1711,
  [SMALL_STATE(46)] = 1730,
  [SMALL_STATE(47)] = 1749,
  [SMALL_STATE(48)] = 1768,
  [SMALL_STATE(49)] = 1787,
  [SMALL_STATE(50)] = 1806,
  [SMALL_STATE(51)] = 1825,
  [SMALL_STATE(52)] = 1844,
  [SMALL_STATE(53)] = 1863,
  [SMALL_STATE(54)] = 1882,
  [SMALL_STATE(55)] = 1901,
  [SMALL_STATE(56)] = 1919,
  [SMALL_STATE(57)] = 1937,
  [SMALL_STATE(58)] = 1955,
  [SMALL_STATE(59)] = 1973,
  [SMALL_STATE(60)] = 1991,
  [SMALL_STATE(61)] = 2009,
  [SMALL_STATE(62)] = 2027,
  [SMALL_STATE(63)] = 2045,
  [SMALL_STATE(64)] = 2063,
  [SMALL_STATE(65)] = 2081,
  [SMALL_STATE(66)] = 2099,
  [SMALL_STATE(67)] = 2117,
  [SMALL_STATE(68)] = 2135,
  [SMALL_STATE(69)] = 2153,
  [SMALL_STATE(70)] = 2171,
  [SMALL_STATE(71)] = 2189,
  [SMALL_STATE(72)] = 2207,
  [SMALL_STATE(73)] = 2225,
  [SMALL_STATE(74)] = 2243,
  [SMALL_STATE(75)] = 2259,
  [SMALL_STATE(76)] = 2268,
  [SMALL_STATE(77)] = 2278,
  [SMALL_STATE(78)] = 2288,
  [SMALL_STATE(79)] = 2296,
  [SMALL_STATE(80)] = 2306,
  [SMALL_STATE(81)] = 2316,
  [SMALL_STATE(82)] = 2324,
  [SMALL_STATE(83)] = 2329,
  [SMALL_STATE(84)] = 2336,
  [SMALL_STATE(85)] = 2343,
  [SMALL_STATE(86)] = 2348,
  [SMALL_STATE(87)] = 2355,
  [SMALL_STATE(88)] = 2362,
  [SMALL_STATE(89)] = 2366,
  [SMALL_STATE(90)] = 2370,
  [SMALL_STATE(91)] = 2374,
  [SMALL_STATE(92)] = 2378,
  [SMALL_STATE(93)] = 2382,
  [SMALL_STATE(94)] = 2386,
  [SMALL_STATE(95)] = 2390,
  [SMALL_STATE(96)] = 2394,
  [SMALL_STATE(97)] = 2398,
  [SMALL_STATE(98)] = 2402,
  [SMALL_STATE(99)] = 2406,
  [SMALL_STATE(100)] = 2410,
  [SMALL_STATE(101)] = 2414,
  [SMALL_STATE(102)] = 2418,
  [SMALL_STATE(103)] = 2422,
  [SMALL_STATE(104)] = 2426,
  [SMALL_STATE(105)] = 2430,
  [SMALL_STATE(106)] = 2434,
  [SMALL_STATE(107)] = 2438,
  [SMALL_STATE(108)] = 2442,
  [SMALL_STATE(109)] = 2446,
  [SMALL_STATE(110)] = 2450,
  [SMALL_STATE(111)] = 2454,
  [SMALL_STATE(112)] = 2458,
  [SMALL_STATE(113)] = 2462,
  [SMALL_STATE(114)] = 2466,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(113),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(101),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(113),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(112),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(111),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(110),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__scoped_identifier_repeat1, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__scoped_identifier_repeat1, 2, 0, 0),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__scoped_identifier_repeat1, 2, 0, 0), SHIFT_REPEAT(104),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__scoped_identifier, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__scoped_identifier, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__scoped_identifier, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__scoped_identifier, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, 0, 4),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 5, 0, 4),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_statement, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_statement, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 3, 0, 1),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 3, 0, 1),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reply_statement, 5, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reply_statement, 5, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__global_scoped_identifier, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__global_scoped_identifier, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defer_statement, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_defer_statement, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assign_statement, 4, 0, 3),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assign_statement, 4, 0, 3),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call_statement, 4, 0, 2),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call_statement, 4, 0, 2),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_illegal_statement, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_illegal_statement, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_statement, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound_statement, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_statement, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound_statement, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_out_event_statement, 6, 0, 8),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_out_event_statement, 6, 0, 8),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defer_statement, 5, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_defer_statement, 5, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defer_statement, 4, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_defer_statement, 4, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reply_statement, 7, 0, 7),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reply_statement, 7, 0, 7),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 5, 0, 5),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 5, 0, 5),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reply_statement, 4, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reply_statement, 4, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 7, 0, 9),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 7, 0, 9),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reply_statement, 6, 0, 7),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reply_statement, 6, 0, 7),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blocking_statement, 2, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_blocking_statement, 2, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_on_statement, 10, 0, 15),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_on_statement, 10, 0, 15),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_on_statement, 9, 0, 14),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_on_statement, 9, 0, 14),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_on_statement, 8, 0, 10),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_on_statement, 8, 0, 10),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_guard_statement, 4, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_guard_statement, 4, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reference, 1, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reference, 1, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [233] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [259] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_on_statement_repeat1, 2, 0, 13),
  [275] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_on_statement_repeat1, 2, 0, 13), SHIFT_REPEAT(87),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__trigger_formal, 1, 0, 6),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_on_statement_repeat1, 2, 0, 12),
  [284] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [286] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__trigger_formal, 3, 0, 11),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 1, 0, 0),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_event, 1, 0, 0),
  [324] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 1, 0, 0),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [330] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_dezyne(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
